services:
  mysqldb:
    image: mysql:5.7
    container_name: appdonations-mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file: ./.env
    environment:
        MYSQL_DATABASE: dbdonations
        MYSQL_TCP_PORT: 3306
        MYSQL_ROOT_PASSWORD: teste
    ports:
        - 3306:3306
    expose:
        - 3306
    healthcheck:
        test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
        timeout: 5s
        retries: 10
  server:
    build:
      context: .
    container_name: appdonations-app
    env_file: ./.env
    depends_on:
      - mysqldb
    environment:
      NODE_ENV: production
      ENV_DATABASE_DIALECT: mysql
      ENV_DATABASE_HOST: mysqldb
      ENV_DATABASE_USERNAME: root
      ENV_DATABASE_PASSWORD: teste
      ENV_DATABASE_DATABASE: dbdonations
      ENV_SECRET_KEY: EXEMPLOSECRETKEY6545645646464565
      ENV_ALGORITHM: aes-256-ctr
      ENV_TOKEN_EXPIRATION: 5000
      ENV_IMAGE_DIRECTORY: /public
    ports:
      - 3333:3333