name: Deploy in production
on: [push]
jobs:

  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get the latest version and compile and build
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.VPS_KEY }}
        port: ${{ secrets.VPS_PORT }}
        script: |
          ls
          cd repositories/donations_web_api/
          
          git pull

          yarn sequelize db:migrate
          yarn build

          pm2 delete donations-api
          pm2 start build/server.js --name donations-api
          pm2 save
